#!/usr/bin/env python3
"""
seal_ecm.py  —  Compile ECM & eigenmode_solver Python source to native .so extensions
                 using Cython, then remove all readable source code.

Protection achieved:
  1. Source → C → .so  (native machine code, not reversible to readable Python)
  2. All .py source files removed from the protected folders
  3. All .c intermediate files removed after compilation
  4. All __pycache__ / .pyc bytecode removed (those ARE reversible)
  5. File permissions set to owner-execute-only (chmod 500)

Usage:
  cd OpenPMUT-Desktop-V2.0.0-Protected
  python3 seal_ecm.py            # compile + strip source
  python3 seal_ecm.py --verify   # quick import test after sealing

The resulting python-backend/ECM/ and python-backend/eigenmode_solver/ folders
contain ONLY .so binary extensions — the app works identically because Python
imports .so files the same way as .py files.
"""

import os
import sys
import glob
import shutil
import subprocess
import argparse
import stat
from pathlib import Path

# ─── Configuration ───────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = SCRIPT_DIR / "python-backend"

# Folders whose .py files will be compiled to .so and source removed
PROTECTED_FOLDERS = [
    BACKEND_DIR / "ECM",
    BACKEND_DIR / "eigenmode_solver",
]

# Files to SKIP (keep as .py because they are not sensitive or are needed as-is)
SKIP_FILES = {
    "__init__.py",      # Package marker — trivial, must remain importable as .py
    "debug_main.py",    # Developer debug entry — remove entirely (not compile)
}

# Files to DELETE entirely (not compile, just remove — dev-only files)
DELETE_FILES = {
    "debug_main.py",
}

# Directories to PRESERVE inside ECM (not removed during sealing)
# saving_folder contains polygon geometry files needed at runtime
KEEP_DIRS = {
    "saving_folder",
}


# ─── Helpers ─────────────────────────────────────────────────────────────────

def find_python_files(folder: Path):
    """Yield .py files in folder (non-recursive, skip __init__.py etc.)"""
    for py_file in sorted(folder.glob("*.py")):
        if py_file.name in SKIP_FILES:
            continue
        yield py_file


def compile_one(py_file: Path):
    """Compile a single .py file to .so using Cython + gcc"""
    module_name = py_file.stem
    folder = py_file.parent

    print(f"  Compiling {py_file.name} → {module_name}*.so ...")

    # We'll use a mini setup.py per file for maximum compatibility
    setup_py = folder / "_cython_build_setup.py"
    setup_content = f"""
import os, sys
from setuptools import setup, Extension
from Cython.Build import cythonize
import numpy

ext = Extension(
    "{module_name}",
    sources=["{py_file.name}"],
    include_dirs=[numpy.get_include()],
)
setup(
    name="{module_name}",
    ext_modules=cythonize(
        [ext],
        compiler_directives={{
            "language_level": "3",
            "boundscheck": False,
            "wraparound": False,
        }},
    ),
)
"""
    setup_py.write_text(setup_content)

    # Build in-place
    result = subprocess.run(
        [sys.executable, str(setup_py), "build_ext", "--inplace"],
        cwd=str(folder),
        capture_output=True,
        text=True,
    )

    # Clean up temp setup.py
    setup_py.unlink(missing_ok=True)

    if result.returncode != 0:
        print(f"    ✗ FAILED: {module_name}")
        print(f"    STDOUT: {result.stdout[-500:]}")
        print(f"    STDERR: {result.stderr[-500:]}")
        return False

    # Find the produced .so file
    so_files = list(folder.glob(f"{module_name}*.so"))
    if not so_files:
        print(f"    ✗ No .so produced for {module_name}")
        return False

    print(f"    ✓ {so_files[0].name}")
    return True


def clean_build_artifacts(folder: Path):
    """Remove .c files, build/ dirs, __pycache__, .pyc, egg-info, etc."""
    # Remove .c files generated by Cython
    for c_file in folder.glob("*.c"):
        c_file.unlink()
        print(f"  Removed {c_file.name}")

    # Remove build directory
    build_dir = folder / "build"
    if build_dir.exists():
        shutil.rmtree(build_dir)
        print(f"  Removed build/")

    # Remove __pycache__
    pycache = folder / "__pycache__"
    if pycache.exists():
        shutil.rmtree(pycache)
        print(f"  Removed __pycache__/")

    # Remove .egg-info
    for egg in folder.glob("*.egg-info"):
        shutil.rmtree(egg)
        print(f"  Removed {egg.name}")

    # Remove temp setup files
    for f in folder.glob("_cython_build_setup*"):
        if f.is_file():
            f.unlink()


def remove_source(folder: Path):
    """Remove .py source files (except __init__.py)"""
    for py_file in sorted(folder.glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        py_file.unlink()
        print(f"  Deleted source: {py_file.name}")


def delete_dev_files(folder: Path):
    """Delete files that should not ship at all"""
    for fname in DELETE_FILES:
        f = folder / fname
        if f.exists():
            f.unlink()
            print(f"  Deleted dev file: {fname}")


def set_permissions(folder: Path):
    """Set .so files to read+execute only for owner (500)"""
    for so_file in folder.glob("*.so"):
        so_file.chmod(stat.S_IRUSR | stat.S_IXUSR)  # 0o500
        print(f"  chmod 500: {so_file.name}")

    # Also lock remaining __init__.py to read-only
    init_py = folder / "__init__.py"
    if init_py.exists():
        init_py.chmod(stat.S_IRUSR)  # 0o400
        print(f"  chmod 400: __init__.py")


def strip_non_py_images(folder: Path):
    """Remove .png, .ipynb, and other non-essential files from eigenmode_solver"""
    removed = 0
    for pattern in ["*.png", "*.ipynb", "*.txt"]:
        for f in folder.glob(pattern):
            f.unlink()
            removed += 1
    if removed:
        print(f"  Removed {removed} non-essential files (.png, .ipynb, .txt)")


# ─── Main ────────────────────────────────────────────────────────────────────

def seal():
    """Main sealing process"""
    print("=" * 70)
    print("  OpenPMUT V2.0.0 ECM Source Code Protection — Cython Compilation")
    print("=" * 70)

    # Pre-check: Cython available?
    try:
        import Cython
        print(f"\n✓ Cython {Cython.__version__} found")
    except ImportError:
        print("\n✗ Cython not installed. Run: pip install cython")
        sys.exit(1)

    # Pre-check: numpy available?
    try:
        import numpy
        print(f"✓ NumPy {numpy.__version__} found")
    except ImportError:
        print("✗ NumPy not installed")
        sys.exit(1)

    success_count = 0
    fail_count = 0

    for folder in PROTECTED_FOLDERS:
        print(f"\n{'─' * 50}")
        print(f"Processing: {folder.relative_to(SCRIPT_DIR)}")
        print(f"{'─' * 50}")

        if not folder.exists():
            print(f"  ⚠ Folder not found, skipping")
            continue

        # Phase 1: Delete dev-only files
        delete_dev_files(folder)

        # Phase 2: Strip non-essential files (images, notebooks) from eigenmode_solver
        if "eigenmode_solver" in str(folder):
            strip_non_py_images(folder)

        # Phase 3: Compile each .py → .so
        py_files = list(find_python_files(folder))
        print(f"\n  Found {len(py_files)} files to compile:\n")

        for py_file in py_files:
            ok = compile_one(py_file)
            if ok:
                success_count += 1
            else:
                fail_count += 1

        # Phase 4: Clean build artifacts (.c, build/, __pycache__, etc.)
        print(f"\n  Cleaning build artifacts...")
        clean_build_artifacts(folder)

        if fail_count == 0:
            # Phase 5: Remove source .py files (only if ALL compiled successfully)
            print(f"\n  Removing source .py files...")
            remove_source(folder)

            # Phase 6: Remove extra subdirectories EXCEPT those in KEEP_DIRS
            for subdir in sorted(folder.iterdir()):
                if subdir.is_dir() and subdir.name not in KEEP_DIRS:
                    shutil.rmtree(subdir)
                    print(f"  Removed {subdir.name}/")

            # Phase 7: Set restrictive permissions
            print(f"\n  Setting restrictive file permissions...")
            set_permissions(folder)
        else:
            print(f"\n  ⚠ Skipping source removal — {fail_count} files failed to compile")

    # Summary
    print(f"\n{'=' * 70}")
    print(f"  Results: {success_count} compiled, {fail_count} failed")
    print(f"{'=' * 70}")

    if fail_count > 0:
        print("\n⚠ Some files failed to compile. Source code was NOT removed.")
        print("  Fix the errors above and re-run.")
        sys.exit(1)
    else:
        print("\n✓ All source code compiled to native .so extensions and removed.")
        print("  The ECM/ and eigenmode_solver/ folders now contain only binary files.")
        print("  The app functions identically — Python imports .so the same as .py.")
        print("\n  Run  python3 seal_ecm.py --verify  to test imports.")


def verify():
    """Quick verification that compiled .so files can be imported"""
    print("\nVerifying compiled modules can be imported...\n")

    ecm_dir = BACKEND_DIR / "ECM"
    eigen_dir = BACKEND_DIR / "eigenmode_solver"

    # Add paths so imports work
    sys.path.insert(0, str(ecm_dir))
    sys.path.insert(0, str(BACKEND_DIR))

    errors = []

    # Check ECM modules
    for so_file in sorted(ecm_dir.glob("*.so")):
        module_name = so_file.name.split(".")[0]
        try:
            __import__(module_name)
            print(f"  ✓ ECM/{module_name}")
        except Exception as e:
            print(f"  ✗ ECM/{module_name}: {e}")
            errors.append(module_name)

    # Check eigenmode_solver modules
    for so_file in sorted(eigen_dir.glob("*.so")):
        module_name = so_file.name.split(".")[0]
        try:
            full_name = f"eigenmode_solver.{module_name}"
            __import__(full_name)
            print(f"  ✓ eigenmode_solver/{module_name}")
        except Exception as e:
            print(f"  ✗ eigenmode_solver/{module_name}: {e}")
            errors.append(full_name)

    if errors:
        print(f"\n✗ {len(errors)} module(s) failed to import")
        sys.exit(1)
    else:
        print(f"\n✓ All compiled modules import successfully")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seal ECM source code via Cython compilation")
    parser.add_argument("--verify", action="store_true", help="Verify compiled modules can be imported")
    args = parser.parse_args()

    if args.verify:
        verify()
    else:
        seal()
