"""
Output API endpoints — simplified.

Serves the PNG files saved by ECM directly, plus basic metadata.
"""

import os
import json
import csv
import io
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, StreamingResponse
from app.routers.simulation import simulation_store

router = APIRouter()


# ------------------------------------------------------------------
# PNG serving endpoints (the simple approach)
# ------------------------------------------------------------------

@router.get("/{simulation_id}/power-plot")
async def get_power_plot(simulation_id: str):
    """
    Serve the frequency_response_plot PNG generated by ECM a11.
    Returns the PNG image directly.
    """
    if simulation_id not in simulation_store:
        raise HTTPException(status_code=404, detail="Simulation not found")

    results = simulation_store[simulation_id]["results"]
    png_path = results.get("power_plot_png", "")

    if not png_path or not os.path.isfile(png_path):
        raise HTTPException(status_code=404, detail="Power plot PNG not found on disk")

    return FileResponse(png_path, media_type="image/png")


@router.get("/{simulation_id}/frames")
async def get_frame_list(simulation_id: str):
    """
    Return metadata about available vibration frame PNGs.
    The frontend uses this to know how many frames exist and their frequencies.
    """
    if simulation_id not in simulation_store:
        raise HTTPException(status_code=404, detail="Simulation not found")

    results = simulation_store[simulation_id]["results"]
    frame_pngs = results.get("frame_pngs", [])
    frame_frequencies = results.get("frame_frequencies", [])

    frames = []
    for i, (path, freq) in enumerate(zip(frame_pngs, frame_frequencies)):
        frames.append({
            "index": i,
            "frequency": freq,
            "exists": os.path.isfile(path),
        })

    return {
        "simulation_id": simulation_id,
        "total_frames": len(frames),
        "frames": frames,
    }


@router.get("/{simulation_id}/frame/{frame_index}")
async def get_frame_png(simulation_id: str, frame_index: int):
    """
    Serve a single vibration frame PNG by index.
    """
    if simulation_id not in simulation_store:
        raise HTTPException(status_code=404, detail="Simulation not found")

    results = simulation_store[simulation_id]["results"]
    frame_pngs = results.get("frame_pngs", [])

    if frame_index < 0 or frame_index >= len(frame_pngs):
        raise HTTPException(status_code=404, detail=f"Frame {frame_index} not found")

    png_path = frame_pngs[frame_index]
    if not os.path.isfile(png_path):
        raise HTTPException(status_code=404, detail=f"Frame file missing: {png_path}")

    return FileResponse(png_path, media_type="image/png")


# ------------------------------------------------------------------
# Summary / metadata
# ------------------------------------------------------------------

@router.get("/{simulation_id}")
async def get_output_summary(simulation_id: str):
    """
    Return simulation result summary (frequencies, power_db, peaks, etc.)
    This is lightweight JSON -- no heavy vibration data.
    """
    if simulation_id not in simulation_store:
        raise HTTPException(status_code=404, detail="Simulation not found")

    results = simulation_store[simulation_id]["results"]

    return {
        "success": True,
        "simulation_id": simulation_id,
        "frequencies": results.get("frequencies", []),
        "power_db": results.get("power_db", []),
        "output_power": results.get("output_power", []),
        "peak_frequency": results.get("peak_frequency", 0),
        "peak_power": results.get("peak_power", 0),
        "bandwidth_3db": results.get("bandwidth_3db", 0),
        "n_frames": len(results.get("frame_pngs", [])),
        "has_power_plot": os.path.isfile(results.get("power_plot_png", "")),
    }


# ------------------------------------------------------------------
# Download endpoints
# ------------------------------------------------------------------

@router.get("/{simulation_id}/download/csv")
async def download_csv(simulation_id: str):
    """Download results as CSV"""
    if simulation_id not in simulation_store:
        raise HTTPException(status_code=404, detail="Simulation not found")

    results = simulation_store[simulation_id]["results"]
    frequencies = results.get("frequencies", [])
    power_db = results.get("power_db", [])

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Frequency (Hz)", "Power (dB)"])
    for f, p in zip(frequencies, power_db):
        writer.writerow([f, p])
    output.seek(0)

    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={
            "Content-Disposition": f"attachment; filename=pmut_results_{simulation_id}.csv"
        },
    )


@router.get("/{simulation_id}/download/json")
async def download_json(simulation_id: str):
    """Download results as JSON"""
    if simulation_id not in simulation_store:
        raise HTTPException(status_code=404, detail="Simulation not found")

    results = simulation_store[simulation_id]["results"]

    # Don't include absolute file paths in the download
    export = {
        "frequencies": results.get("frequencies", []),
        "output_power": results.get("output_power", []),
        "power_db": results.get("power_db", []),
        "peak_frequency": results.get("peak_frequency"),
        "peak_power": results.get("peak_power"),
        "bandwidth_3db": results.get("bandwidth_3db"),
    }

    output = io.StringIO()
    json.dump(export, output, indent=2)
    output.seek(0)

    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="application/json",
        headers={
            "Content-Disposition": f"attachment; filename=pmut_results_{simulation_id}.json"
        },
    )
